CREATE DATABASE Biblioteca_Practica;

--CREAREA TABELELOR
	-CARTI
		ID_CARTE
		DENUMIRE
		AUTOR_ID
		NR_PAG
		EDITURA_ID
		DOMENIU_ID
		LIMBA

CREATE TABLE AUTOR
(
	ID_AUTOR INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(100),
	PRENUME VARCHAR(100),
	DATA_NASTERE DATE
)

CREATE TABLE EDITURA
(
	ID_EDITURA INT PRIMARY KEY IDENTITY(1,1),
	DENUMIRE VARCHAR(50)
)

CREATE TABLE DOMENIU
(
	ID_DOMENIU INT PRIMARY KEY IDENTITY(1,1),
	DOMENIU VARCHAR(100)
)

CREATE TABLE CARTE
(
	ID_CARTE INT PRIMARY KEY IDENTITY(1,1),
	DENUMIRE_CARTE VARCHAR(100),
	NR_PAG INT,
	LIMBA VARCHAR(5),
	ID_AUTOR INT FOREIGN KEY REFERENCES AUTOR(ID_AUTOR),
	ID_EDITURA INT FOREIGN KEY REFERENCES EDITURA(ID_EDITURA),
	ID_DOMENIU INT FOREIGN KEY REFERENCES DOMENIU(ID_DOMENIU)
)

CREATE TABLE UTILIZATOR
(
	ID_USER INT PRIMARY KEY IDENTITY(1,1),
	NUME_UTILIZATOR VARCHAR(50),
	PAROLA VARCHAR(50),
	STATUT VARCHAR(20),
	NUME VARCHAR(100),
	PRENUME VARCHAR(100),
	SEX CHAR(3)
)

CREATE TABLE CITITOR
(
	ID_CITITOR INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(100),
	PRENUME VARCHAR(100),
	NR_TEL VARCHAR(20),
	DATA_NASTERE DATE,
	ADRESA VARCHAR(100)
)

CREATE TABLE IMPRUMUT
(
	ID_IMPRUMUT INT PRIMARY KEY IDENTITY(1,1),
	ID_CARTE INT FOREIGN KEY REFERENCES CARTE(ID_CARTE),
	ID_CITITOR INT FOREIGN KEY REFERENCES CITITOR(ID_CITITOR),
	ID_USER INT FOREIGN KEY REFERENCES UTILIZATOR(ID_USER),
	DATA_IMPRUMUT DATE,
	DATA_ESTIM_RETURN DATE,
	DATA_RETURN DATE
)

--INTRODUCEREA DATELOR
INSERT INTO EDITURA(DENUMIRE)
VALUES('TREI'),			--1
		('Life Style'),	--2
		('Court'),		--3
		('RAO'),		--4
		('Humans'),		--5
		('Top 10'),		--6
		('Univers'),	--7
		('Bestseller'),	--8
		('Cartier');	--9

INSERT INTO DOMENIU(DOMENIU)
VALUES('Pentru copii'),				--1
		('Limbi straine'),			--2
		('Fictiune'),				--3
		('Calatorie'),				--4
		('Dezvoltare personala'),	--5
		('Psihologie'),				--6
		('Stiinta'),				--7
		('Manuale'),				--8
		('Filosofie');				--9

INSERT INTO AUTOR(NUME, PRENUME,DATA_NASTERE)
VALUES('Eminescu', 'Mihai', '1850-01-15'),	--11
		('Tolle', 'Eckart', '1910-05-23'),	--12
		('Russo', 'Andreea', '1979-09-18'),	--13
		('Mc Guire', 'Jamie', '2000-11-07'),--16
		('Strelecky', 'John', '1997-02-20'),--17
		('Hawkins', 'Paula', '1987-12-11');	--118

INSERT INTO CARTE(DENUMIRE_CARTE, NR_PAG, LIMBA, ID_AUTOR, ID_EDITURA, ID_DOMENIU)
VALUES('Luceafarul', 50, 'RO', 11, 6, 9),						--10
		('The power of now', 245, 'ENG', 12, 2, 5),				--11
		('MoArt', 178, 'RO', 13, 6 ,9),							--12
		('Radosti nacenaetsia cevodnia', 450, 'RU', 16, 1,3);	--13

INSERT INTO UTILIZATOR(NUME_UTILIZATOR, PAROLA, STATUT, NUME, PRENUME, SEX, Nr_Tel)
VALUES('admin', '123', 'admin', 'Chitic', 'Giulia', 'f', '075678987'),		--1
		('maria_m', 'm123', 'user', 'Mardari', 'Maria', 'f', '067898652');	--2

INSERT INTO CITITOR(NUME, PRENUME, NR_TEL, DATA_NASTERE, ADRESA)
VALUES('Vasilevici', 'Anton', '078651467', '2000-09-12', 'mun.Chisinau str.Paris8'),	--1
		('Sorc', 'Anastasia', '078976524', '2003-09-01', 'or. Ialoveni str.Florilor5');	--2

INSERT INTO IMPRUMUT(ID_CARTE, ID_CITITOR, DATA_IMPRUMUT, DATA_ESTIM_RETURN, DATA_RETURN)
VALUES(10, 1, '2024-05-20', '2024-05-31', null),
		(11, 2, '2024-05-18', '2023-05-29', '2024-05-21');


--INTEROGARI
SELECT ID_CARTE, DENUMIRE_CARTE, A.NUME+' '+A.PRENUME AS AUTOR, E.DENUMIRE AS EDITURA, D.DOMENIU, NR_PAG, LIMBA
FROM CARTE C INNER JOIN AUTOR A ON C.ID_AUTOR=A.ID_AUTOR
				INNER JOIN EDITURA E ON C.ID_EDITURA=E.ID_EDITURA
				INNER JOIN DOMENIU D ON C.ID_DOMENIU=D.ID_DOMENIU;

SELECT C.DENUMIRE_CARTE, A.NUME+A.PRENUME AS AUTOR, D.DOMENIU, E.DENUMIRE, C.LIMBA, C.AN_publicare ,C.CANTITATE
FROM CARTE C INNER JOIN AUTOR A ON C.ID_AUTOR=A.ID_AUTOR
				INNER JOIN EDITURA E ON C.ID_EDITURA=E.ID_EDITURA
				INNER JOIN DOMENIU D ON C.ID_DOMENIU=D.ID_DOMENIU;
			

SELECT *
FROM CARTE C INNER JOIN AUTOR A ON C.ID_AUTOR=A.ID_AUTOR
WHERE DENUMIRE_CARTE LIKE'%' OR A.NUME LIKE'%' OR A.PRENUME LIKE'%'


SELECT NUME, PRENUME, DATA_NASTERE FROM AUTOR;

SELECT * FROM UTILIZATOR;

SELECT NUME, PRENUME, NR_TEL, DATA_NASTERE, ADRESA FROM CITITOR;
SELECT * FROM CITITOR WHERE ID_CITITOR=1;
SELECT * FROM CITITOR WHERE NUME LIKE'Vas%' or PRENUME LIKE 'Ana%' or NR_TEL LIKE '0786%';

SELECT ID_AUTOR FROM AUTOR WHERE NUME=@NUME, PRENUME=@PRENUME;

--Comenzi sql
SELECT NUME_UTILIZATOR, PAROLA
FROM UTILIZATOR
WHERE NUME_UTILIZATOR=@user AND PAROLA=@pass;

INSERT INTO AUTOR (NUME, PRENUME, DATA_NASTERE)
VALUES (@NUME, @PRENUME, @DATA_NASTERE);

INSERT INTO UTILIZATOR(NUME_UTILIZATOR, PAROLA, NUME, PRENUME, SEX, Nr_Tel, STATUT)
VALUES(@NUME_UTILIZATOR, @PAROLA, @NUME, @PRENUME, @SEX,@Nr_Tel, 'user');

INSERT INTO CITITOR(NUME, PRENUME, NR_TEL, DATA_NASTERE, ADRESA)
VALUES(@NUME, @PRENUME, @NR_TEL, @DATA_NASTERE, @ADRESA);


UPDATE CITITOR
SET NUME = @NUME, PRENUME=@PRENUME, NR_TEL=@NR_TEL, DATA_NASTERE=@DATA_NASTERE, ADRESA=@ADRESA
WHERE ID_CITITOR=@ID_CITITOR;
